# -*- coding: utf-8 -*-
"""Дмитриева Криличевский Ситдиков матстат ср4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_HbxpgYf4i_odgAb52-Kv6c5gUR05CWo

# 1. СР4 по анализу гистограммы(Занятие 3)

Вариант 3. Медиана = 50,6. Число интервалов (Скотт, 8–16): k = 8.
"""

from google.colab import files
files.upload()

import matplotlib.pyplot as plt
import matplotlib.image as mpimg

img = mpimg.imread('./variant_3.png')
plt.imshow(img)

import numpy as np


counts = [1, 2, 2, 2, 3, 4, 4, 6, 7, 7]
bins = [0, 10, 20, 30, 40, 50, 66, 77, 89]

# ШАГ 1: Выборочные оценки
x_bar = np.mean(bins)
s2 = np.var(bins, ddof=1)
s = np.sqrt(s2)


print("Выборочные оценки:")
print(f"  Среднее:      x̄ = {x_bar}")
print(f"  Дисперсия:    s² = {s2}")
print(f"  Ст. откл.:    s = {s}")

# Центры столбцов
centers = [(bins[i] + bins[i+1]) / 2 for i in range(len(bins)-1)]
widths = [bins[i+1] - bins[i] for i in range(len(bins)-1)]

plt.figure(figsize=(10,6))

# Строим столбцы
bars = plt.bar(
    centers,
    counts,
    width=widths,
    color="#5b8db8",
    edgecolor="black",
    align="center"
)

# Подписываем частоты
for x, y in zip(centers, counts):
    plt.text(x, y + 0.5, str(y), ha='center', fontsize=12)


median = 50.6
plt.axvline(
    median,
    color="green",
    linestyle="--",
    linewidth=2,
    label=f"Медиана = {median}"
)

plt.axvline(
    x_bar,
    color="red",
    linestyle="--",
    linewidth=2,
    label=f"Среднее = {x_bar}"
)
s1 = x_bar - s
s2 = x_bar + s
plt.axvline(
    s1,
    color="blue",
    linestyle="--",
    linewidth=2,
    label=f"x̄ - s = {s1}"
)
plt.axvline(
    s2,
    color="blue",
    linestyle="--",
    linewidth=2,
    label=f"x̄ + s = {s2}"
)

plt.xlabel("Значение признака", fontsize=13)
plt.ylabel("Частота", fontsize=13)

plt.grid(axis='y', linestyle='--', alpha=0.5)

plt.legend()

plt.tight_layout()
plt.show()

"""2.1 Количество мод: 1 (частота 34)

2.2 Симметрия: слабо отрицательный коэфф. симметрии. Слева есть маленький хвост, но в общем распределение похоже на нармальное.

2.3 50.6 > 42.7 - Медиана больше среднего. Среднее чувствительно к выбросам, его значение оказалось меньше из-за хвоста слева. Наш вывод подтверждается.

2.4 Бимодальности нет. Признаков выбросов нет, только крайние значения слева.

2.5 Мера центра - медиана.

2.6 Нормальное. Симметричный колокол, один пик
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy import stats


counts = [9, 12, 10, 28, 19, 24, 10, 8]
bins = [29, 34, 39, 44, 49, 54, 59, 64, 69]

# Вычисляем середины интервалов
midpoints = [(bins[i] + bins[i+1]) / 2 for i in range(len(bins)-1)]

# Создаем расширенный массив данных для точных вычислений
expanded_data = []
for i in range(len(midpoints)):
    expanded_data.extend([midpoints[i]] * counts[i])

# Основные выборочные характеристики
print("=" * 60)
print("ВЫБОРОЧНЫЕ ХАРАКТЕРИСТИКИ ИНТЕРВАЛЬНОГО РЯДА")
print("=" * 60)

#  Объем выборки
n = sum(counts)
print(f"\n1. Объем выборки (n): {n}")

# Центры столбцов
centers = [(bins[i] + bins[i+1]) / 2 for i in range(len(bins)-1)]
widths = [bins[i+1] - bins[i] for i in range(len(bins)-1)]

#  Среднее арифметическое (математическое ожидание)
mean = np.mean(expanded_data)
print(f"\n2. Среднее арифметическое (x̄): {mean:.4f}")

#  Дисперсия (смещенная и несмещенная)
variance_biased = np.var(expanded_data, ddof=0)  # смещенная (для генеральной совокупности)
variance_unbiased = np.var(expanded_data, ddof=1)  # несмещенная (для выборки)
print(f"\n3. Дисперсия:")
print(f"   - Смещенная (σ²): {variance_biased:.4f}")
print(f"   - Несмещенная (s²): {variance_unbiased:.4f}")

#  Среднее квадратическое отклонение (стандартное отклонение)
std_biased = np.std(expanded_data, ddof=0)
std_unbiased = np.std(expanded_data, ddof=1)
print(f"\n4. Среднее квадратическое отклонение:")
print(f"   - Смещенное (σ): {std_biased:.4f}")
print(f"   - Несмещенное (s): {std_unbiased:.4f}")


#  Медиана (значение, которое делит выборку пополам)
median = np.median(expanded_data)
print(f"\n6. Медиана (Me): {median:.4f}")

lower_bound = mean - std_unbiased
upper_bound = mean + std_unbiased

print(f"\nИнтервал: [{lower_bound:.4f}; {upper_bound:.4f}]")
#  Асимметрия и эксцесс
skewness = stats.skew(expanded_data)
kurtosis = stats.kurtosis(expanded_data)
print(f"\n12. Форма распределения:")
print(f"   - Коэффициент асимметрии: {skewness:.4f}")
print(f"   - Коэффициент эксцесса: {kurtosis:.4f}")

print("\n" + "=" * 60)


plt.figure(figsize=(10,6))

for x, y in zip(centers, counts):
    plt.text(x, y + 0.5, str(y), ha='center', fontsize=12)

bars = plt.bar(
    centers,
    counts,
    width=widths,
    color="#5b8db8",
    edgecolor="black",
    align="center"
)

plt.axvline(
    median,
    color="green",
    linestyle="--",
    linewidth=2,
    label=f"Медиана = {median:.4f}"
)

plt.axvline(
    mean,
    color="red",
    linestyle="--",
    linewidth=2,
    label=f"Среднее = {mean:.4f}"
)

plt.axvline(
    lower_bound,
    color="blue",
    linestyle="--",
    linewidth=2,
    label=f"x̄ - s = {lower_bound:.4f}"
)
plt.axvline(
    upper_bound,
    color="blue",
    linestyle="--",
    linewidth=2,
    label=f"x̄ + s = {upper_bound:.4f}"
)

plt.xlabel("Значение признака", fontsize=13)
plt.ylabel("Частота", fontsize=13)

plt.grid(axis='y', linestyle='--', alpha=0.5)

plt.legend()

plt.tight_layout()
plt.show()